version: "3.3"
services:
  mysql:
    container_name: mysql
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: psh_challenge
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  server:
    container_name: server
    depends_on:
      mysql:
        condition: service_healthy
    build: ./server/
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
    restart: always

  client:
    container_name: client
    build: ./client/
    ports:
      - "3000:3000"
